### ISSUE TITLE
Create the Menu

### ISSUE THREAD

**Issue by RoachxD** [RoachxD/EloBuddy#22]
I think that we should make a separate class for the Menu and only the ChampionBase Menu should be "Dynamic".

**Comment by ghost** [comment]
Status changed to In Progress 2:38 PM here in Italy.
Working on a common menu for every addon.

**Comment by ghost** [comment]
[readme.rtf](https://files.zenhub.io/5682a1fb69393e035f1f1cb7)
Here is the readme for check vars etc of the current custom menu.
It is a template with the best things every addon here on the aio needs.

**Comment by ghost** [comment]
The common menu is moved in the Old Code folder.
